//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharpfirstpass
{
	public interface App42NativePushListener
	{
		void onDeviceToken (String regId);
		void onMessage (String message);
		void onError (String error);

	}
}

